baseURL = 'https://jonahweissman.github.io/blog/'
languageCode = 'en-us'
title = 'Blog'

[params]
  description = 'A simple blog'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
